# Docker Compose for Literati Library App - Client Only
version: '3.8'

services:
  # Client (React SPA)
  client:
    build:
      context: ./client2
      dockerfile: Dockerfile
    image: literati-client:latest
    container_name: literati-client
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:5000}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_AI_SERVICE_URL=${VITE_AI_SERVICE_URL:-http://localhost:8000}
      - NODE_ENV=production
    networks:
      - literati-network
    volumes:
      - client-logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  literati-network:
    driver: bridge

volumes:
  client-logs:
    driver: local