# Development overrides for docker-compose
version: '3.8'

services:
  client:
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
      - NODE_ENV=development
    volumes:
      - ./client2/src:/app/src:ro
    command: npm run dev

  server:
    environment:
      - NODE_ENV=development
    volumes:
      - ./server2/src:/app/src:ro
      - ./server2/uploads:/app/uploads
    command: npm run dev

  ai-service:
    volumes:
      - ./ai-service:/app:ro
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload