# Development overrides for docker-compose
version: '3.8'

services:
  client:
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
      - NODE_ENV=development
    volumes:
      - ./client2/src:/app/src:ro
    command: pnpm run dev