name: Setup pnpm via Corepack
description: Enables Corepack and activates a pinned pnpm version
inputs:
  version:
    description: pnpm version to activate
    required: false
    default: 8.15.6
runs:
  using: composite
  steps:
    - shell: bash
      env:
        PNPM_VERSION: ${{ inputs.version }}
      run: |
        set -euo pipefail

        # Update Corepack to latest version to avoid signature issues
        npm install -g corepack@latest
        corepack enable

        VER="${PNPM_VERSION}"
        if [[ "$VER" == "latest" || "$VER" == *".x"* || -z "$VER" ]]; then
          VER=8.15.6
        fi
        echo "Activating pnpm@$VER via Corepack"
        corepack prepare pnpm@${VER} --activate
